version: '3.8'

services:
  app:
    build:
      context: ./NextApp
      dockerfile: Dockerfile
      args:
        - MONGODB_URI=${MONGODB_URI}
        - SHEET_ID=${SHEET_ID}
        - GOOGLE_API_KEY=${GOOGLE_API_KEY}
        - RUN_ON_STARTUP=${RUN_ON_STARTUP}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-app.loadbalancer.server.port=3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - SHEET_ID=${SHEET_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - RUN_ON_STARTUP=${RUN_ON_STARTUP}
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - dockploy-public
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  dockploy-public:
    external: true