version: '3.8'

services:
  app:
    build:
      context: ./NextApp
      dockerfile: Dockerfile
      args:
        - MONGODB_URI=${MONGODB_URI}
        - SHEET_ID=${SHEET_ID}
        - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - SHEET_ID=${SHEET_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - NODE_ENV=production
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./NextApp:/app
      - /app/node_modules
      - /var/log/cron.log:/var/log/cron.log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=woxsen
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo_data: