version: "3.8"
services:
  app:
    build:
      context: ./NextApp  # Ensure it correctly points to the NextApp directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env  # Loads environment variables from .env file
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env  # Optional: Load MongoDB env vars if needed

volumes:
  mongo_data:
