version: "3.8"

services:
  app:
    build:
      context: ./NextApp  # Ensure it correctly points to the NextApp directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env  # Loads environment variables
    depends_on:
      - mongo
    volumes:
      - ./NextApp:/app  # Mount local files for live updates
    command: ["sh", "-c", "crond -b && pm2-runtime start 'npx next start'"]

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env  # Optional: Load MongoDB env vars if needed

volumes:
  mongo_data:
