version: "3.8"

services:
  app:
    build:
      context: ./NextApp  # Path to your Next.js app directory
      dockerfile: Dockerfile
      args:
        MONGODB_URI: ${MONGODB_URI}
        SHEET_ID: ${SHEET_ID}
    ports:
      - "3000:3000"
    env_file:
      - .env  # Loads environment variables for runtime
    depends_on:
      - mongo
    volumes:
      - ./NextApp:/app  # Live code mounting
    command: ["sh", "-c", "crond -b && pm2-runtime start 'npx next start'"]

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env  # Loads MongoDB env vars

volumes:
  mongo_data:
