[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmds = ["pnpm install --legacy-peer-deps"]

[phases.build]
cmds = ["pnpm run build"]

[phases.start]
cmd = "pnpm run start"
env = { PORT = "3000" }
