[phases.setup]
# Install Bun + Node
nixPkgs = ["bun", "nodejs_20"]

[phases.install]
# Use Bun to install using bun.lock
cmds = ["bun install --no-save"]

[phases.build]
# Build using Node (Next.js requires full worker_threads API)
cmds = ["node ./node_modules/next/dist/bin/next build"]

[phases.start]
# Run using Node as well
cmd = "node ./node_modules/next/dist/bin/next start -p $PORT"
env = { PORT = "3000" }
