[phases.setup]
nixPkgs = ["bun"]   # Use Bun runtime only

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]

[phases.start]
cmd = "bun run start"
env = { PORT = "3000" }
